services:
  postgres-soe-prod:
    image: postgres:16
    container_name: postgres-soe-prod
    restart: unless-stopped
    ports:
      - '${HOST_DOCKER_PG_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-soe-prod-data:/var/lib/postgresql/data
    networks:
      - soe-prod-network

  backend-prod-soev2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-prod-soev2
    restart: unless-stopped
    ports:
      - '${HOST_DOCKER_BACKEND_PORT}:${PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      PORT: ${PORT}
      MAIL_API_KEY: ${MAIL_API_KEY}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_USER_PWD: ${MAIL_USER_PWD}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_FROM: ${MAIL_FROM}
    depends_on:
      - postgres-soe-prod
    volumes:
      - /uploads:/app/uploads
      - /logs:/app/logs
    networks:
      - soe-prod-network

volumes:
  postgres-soe-prod-data:
  uploads-data:
  logs-data:

networks:
  soe-prod-network:
    name: soe-prod-network
    driver: bridge
