services:
  soe-postgres:
    image: postgres:16
    restart: always
    ports:
      - '${HOST_DOCKER_PG_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: soe-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
