// src/common/constants/permissions.constant.ts

export const PERMISSIONS = {
  USERS: {
    ACCESS: 'user.access',
    READ: 'user.read',
    CREATE: 'user.create',
    UPDATE: 'user.update',
    DELETE: 'user.delete',
    EXPORT: 'user.export',
    APPROVE: 'user.approve',
    ASSIGN: 'user.assign',
  },
  ROLES: {
    ACCESS: 'role.access',
    READ: 'role.read',
    CREATE: 'role.create',
    UPDATE: 'role.update',
    DELETE: 'role.delete',
    EXPORT: 'role.export',
    APPROVE: 'role.approve',
    ASSIGN: 'role.assign',
  },
  PERMISSIONS: {
    ACCESS: 'permission.access',
    READ: 'permission.read',
    CREATE: 'permission.create',
    UPDATE: 'permission.update',
    DELETE: 'permission.delete',
    EXPORT: 'permission.export',
    APPROVE: 'permission.approve',
    ASSIGN: 'permission.assign',
  },
  MODULES: {
    ACCESS: 'module.access',
    READ: 'module.read',
    CREATE: 'module.create',
    UPDATE: 'module.update',
    DELETE: 'module.delete',
    EXPORT: 'module.export',
    APPROVE: 'module.approve',
    ASSIGN: 'module.assign',
  },
  COMPANIES: {
    ACCESS: 'company.access',
    READ: 'company.read',
    CREATE: 'company.create',
    UPDATE: 'company.update',
    DELETE: 'company.delete',
    EXPORT: 'company.export',
    APPROVE: 'company.approve',
    ASSIGN: 'company.assign',
  },
  BUSINESS_UNITS: {
    ACCESS: 'businessUnit.access',
    READ: 'businessUnit.read',
    CREATE: 'businessUnit.create',
    UPDATE: 'businessUnit.update',
    DELETE: 'businessUnit.delete',
    EXPORT: 'businessUnit.export',
    APPROVE: 'businessUnit.approve',
    ASSIGN: 'businessUnit.assign',
  },
};
