// src/common/constants/permissions.constant.ts

export const PERMISSIONS = {
  USERS: {
    ACCESS: 'user.access',
    READ: 'user.read',
    CREATE: 'user.create',
    UPDATE: 'user.update',
    DELETE: 'user.delete',
    EXPORT: 'user.export',
    APPROVE: 'user.approve',
    ASSIGN: 'user.assign',
  },
  ROLES: {
    ACCESS: 'role.access',
    READ: 'role.read',
    CREATE: 'role.create',
    UPDATE: 'role.update',
    DELETE: 'role.delete',
    EXPORT: 'role.export',
    APPROVE: 'role.approve',
    ASSIGN: 'role.assign',
  },
  PERMISSIONS: {
    ACCESS: 'permission.access',
    READ: 'permission.read',
    CREATE: 'permission.create',
    UPDATE: 'permission.update',
    DELETE: 'permission.delete',
    EXPORT: 'permission.export',
    APPROVE: 'permission.approve',
    ASSIGN: 'permission.assign',
  },
  MODULES: {
    ACCESS: 'module.access',
    READ: 'module.read',
    CREATE: 'module.create',
    UPDATE: 'module.update',
    DELETE: 'module.delete',
    EXPORT: 'module.export',
    APPROVE: 'module.approve',
    ASSIGN: 'module.assign',
  },
  COMPANIES: {
    ACCESS: 'company.access',
    READ: 'company.read',
    CREATE: 'company.create',
    UPDATE: 'company.update',
    DELETE: 'company.delete',
    EXPORT: 'company.export',
    APPROVE: 'company.approve',
    ASSIGN: 'company.assign',
  },
  BUSINESS_UNITS: {
    ACCESS: 'businessUnit.access',
    READ: 'businessUnit.read',
    CREATE: 'businessUnit.create',
    UPDATE: 'businessUnit.update',
    DELETE: 'businessUnit.delete',
    EXPORT: 'businessUnit.export',
    APPROVE: 'businessUnit.approve',
    ASSIGN: 'businessUnit.assign',
  },
  POSITIONS: {
    ACCESS: 'position.access',
    READ: 'position.read',
    CREATE: 'position.create',
    UPDATE: 'position.update',
    DELETE: 'position.delete',
    EXPORT: 'position.export',
    APPROVE: 'position.approve',
    ASSIGN: 'position.assign',
  },
  STRATEGIC_PLANS: {
    ACCESS: 'strategicPlan.access',
    READ: 'strategicPlan.read',
    CREATE: 'strategicPlan.create',
    UPDATE: 'strategicPlan.update',
    DELETE: 'strategicPlan.delete',
    EXPORT: 'strategicPlan.export',
    APPROVE: 'strategicPlan.approve',
    ASSIGN: 'strategicPlan.assign',
  },
  STRATEGIC_VALUES: {
    ACCESS: 'strategicValue.access',
    READ: 'strategicValue.read',
    CREATE: 'strategicValue.create',
    UPDATE: 'strategicValue.update',
    DELETE: 'strategicValue.delete',
    EXPORT: 'strategicValue.export',
    APPROVE: 'strategicValue.approve',
    ASSIGN: 'strategicValue.assign',
  },
  STRATEGIC_SUCCESS_FACTORS: {
    ACCESS: 'strategicSuccessFactor.access',
    READ: 'strategicSuccessFactor.read',
    CREATE: 'strategicSuccessFactor.create',
    UPDATE: 'strategicSuccessFactor.update',
    DELETE: 'strategicSuccessFactor.delete',
    EXPORT: 'strategicSuccessFactor.export',
    APPROVE: 'strategicSuccessFactor.approve',
    ASSIGN: 'strategicSuccessFactor.assign',
  },
  OBJECTIVES: {
    ACCESS: 'objective.access',
    READ: 'objective.read',
    CREATE: 'objective.create',
    UPDATE: 'objective.update',
    DELETE: 'objective.delete',
    EXPORT: 'objective.export',
    APPROVE: 'objective.approve',
    ASSIGN: 'objective.assign',
  },
  INDICATORS: {
    ACCESS: 'indicator.access',
    READ: 'indicator.read',
    CREATE: 'indicator.create',
    UPDATE: 'indicator.update',
    DELETE: 'indicator.delete',
    EXPORT: 'indicator.export',
    APPROVE: 'indicator.approve',
    ASSIGN: 'indicator.assign',
  },
  OBJECTIVE_GOALS: {
    ACCESS: 'objectiveGoal.access',
    READ: 'objectiveGoal.read',
    CREATE: 'objectiveGoal.create',
    UPDATE: 'objectiveGoal.update',
    DELETE: 'objectiveGoal.delete',
    EXPORT: 'objectiveGoal.export',
    APPROVE: 'objectiveGoal.approve',
    ASSIGN: 'objectiveGoal.assign',
  },
  OBJECTIVES_PARTICIPANTS: {
    ACCESS: 'objectiveParticipant.access',
    READ: 'objectiveParticipant.read',
    CREATE: 'objectiveParticipant.create',
    UPDATE: 'objectiveParticipant.update',
    DELETE: 'objectiveParticipant.delete',
    EXPORT: 'objectiveParticipant.export',
    APPROVE: 'objectiveParticipant.approve',
    ASSIGN: 'objectiveParticipant.assign',
  },
  STRATEGIC_PROJECTS: {
    ACCESS: 'strategicProject.access',
    READ: 'strategicProject.read',
    CREATE: 'strategicProject.create',
    UPDATE: 'strategicProject.update',
    DELETE: 'strategicProject.delete',
    EXPORT: 'strategicProject.export',
    APPROVE: 'strategicProject.approve',
    ASSIGN: 'strategicProject.assign',
  },
  PROJECT_PARTICIPANTS: {
    ACCESS: 'projectParticipant.access',
    READ: 'projectParticipant.read',
    CREATE: 'projectParticipant.create',
    UPDATE: 'projectParticipant.update',
    DELETE: 'projectParticipant.delete',
    EXPORT: 'projectParticipant.export',
    APPROVE: 'projectParticipant.approve',
    ASSIGN: 'projectParticipant.assign',
  },
  PROJECT_FACTORS: {
    ACCESS: 'projectFactor.access',
    READ: 'projectFactor.read',
    CREATE: 'projectFactor.create',
    UPDATE: 'projectFactor.update',
    DELETE: 'projectFactor.delete',
    EXPORT: 'projectFactor.export',
    APPROVE: 'projectFactor.approve',
    ASSIGN: 'projectFactor.assign',
  },
  PROJECT_TASKS: {
    ACCESS: 'projectTask.access',
    READ: 'projectTask.read',
    CREATE: 'projectTask.create',
    UPDATE: 'projectTask.update',
    DELETE: 'projectTask.delete',
    EXPORT: 'projectTask.export',
    APPROVE: 'projectTask.approve',
    ASSIGN: 'projectTask.assign',
  },
  PRIORITIES: {
    ACCESS: 'priority.access',
    READ: 'priority.read',
    CREATE: 'priority.create',
    UPDATE: 'priority.update',
    DELETE: 'priority.delete',
    EXPORT: 'priority.export',
    APPROVE: 'priority.approve',
    ASSIGN: 'priority.assign',
  },
  PERFORMANCE: {
    ACCESS: 'performance.access',
    READ: 'performance.read',
    CREATE: 'performance.create',
    UPDATE: 'performance.update',
    DELETE: 'performance.delete',
    EXPORT: 'performance.export',
    APPROVE: 'performance.approve',
    ASSIGN: 'performance.assign',
  },
};
